module.exports = {
  LOGIN_USER: "LOGIN_USER",
  POST_STATUS: "POST_STATUS",
  INCREMENT_LIKE: "INCREMENT_LIKE",
  SHOW_POST_COMMENT: "SHOW_POST_COMMENT",
  POST_COMMENT: "POST_COMMENT",
  UPLOAD_IMAGE: "UPLOAD_IMAGE",
  JOIN_EVENT: "JOIN_EVENT",
  POST_GOAL_SESSION: "POST_GOAL_SESSION"
}
